name: Build and run simple ksmt tests

on:
  push:
    branches:
      - main
      - vavilovm/develop/symfpu-yices-asarray-wip

  pull_request:
    types: [ opened, edited ]
    branches:
      - main

jobs:
  run_tests:
    name: Run tests
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
          cache: gradle

      - name: Build and run simple tests on Linux or Windows
        uses: gradle/gradle-build-action@v2
        if: runner.os != 'macOS'
        with:
          arguments: |
            :ksmt-symfpu:build
             --no-daemon
             --continue
             -PrunBenchmarksBasedTests=false

      - name: Upload ksmt test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ksmt-tests-report-${{ matrix.os }}
          path: ./**/build/reports/tests/test/
