name: Build and run benchmark tests

on:
  workflow_dispatch:


env:
  TEST_DATA_REVISION: 0.2.1

jobs:
  prepare_test_data:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare test data (cache)
        id: test-data-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-test-data
        with:
          key: test-data-${{ env.TEST_DATA_REVISION }}-${{ matrix.os }}
          path: ksmt-test/testData/testData.zip

      - name: Set up JDK 1.8
        if: steps.test-data-cache.outputs.cache-hit != 'true'
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
          cache: gradle

      - name: Prepare test data (download)
        if: steps.test-data-cache.outputs.cache-hit != 'true'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :ksmt-test:downloadPreparedSmtLibBenchmarkTestData
            --no-daemon
            -PtestDataRevision=${{ env.TEST_DATA_REVISION }}

  run_tests:
    needs: [ prepare_test_data ]
    continue-on-error: true
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        test: [ SymFPUBenchmarksBasedTest.testQF_ABVFP, SymFPUBenchmarksBasedTest.testQF_BVFP, SymFPUBenchmarksBasedTest.testQF_FP ]

    name: Run ${{ matrix.test }} on ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Prepare test data (cache)
        id: test-data-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-test-data
        with:
          key: test-data-${{ env.TEST_DATA_REVISION }}-${{ matrix.os }}
          path: ksmt-test/testData/testData.zip

      - name: Check test data downloaded
        if: steps.test-data-cache.outputs.cache-hit != 'true'
        run: |
          echo "Test data is not available"
          exit 1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: 'zulu'
          cache: gradle

      # Since ksmt-test/testData/testData.zip exists task will not download it again
      - name: Prepare test data (unpack)
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :ksmt-test:downloadPreparedSmtLibBenchmarkTestData
            --no-daemon
            -PtestDataRevision=${{ env.TEST_DATA_REVISION }}

      - name: Build project
        uses: gradle/gradle-build-action@v2
        if: always()
        with:
          arguments: |
            build
            --no-daemon

      - name: Run ${{ matrix.test }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            :ksmt-test:test --tests  ${{ format('"org.ksmt.test.benchmarks.{0}"', matrix.test) }}
            --no-daemon
            --continue
            -PrunBenchmarksBasedTests=true

      - name: Upload ksmt test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ${{ format('bench-{0}-{1}', matrix.test) }}
          path: ksmt-test/data.csv


